### ISSUE TITLE
频繁出现Http request errored

### ISSUE THREAD

**Issue by Pearlulu** [Billyzou0741326/bilibili-raffle-js#29]
```
 [2020-02-26 11:39:28]   
 Error: Http request errored
    at ClientRequest.xhr.request.on.on.on (/data/bilibili-raffle-js/src/net/xhr.js:38:51)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
```
最近经常这样报错。
另外可能会出现卡在重连这里没触发任何事件。
```
 [2020-02-25 23:43:41]   2097142034574   @5148           storm           节奏风暴
 [2020-02-25 23:44:25]   [ Server ] Trying to reconnect to ws://bili.minamiktr.com/ws:8999 ...
 [2020-02-26 00:00:09]   视频观看成功
 [2020-02-26 00:00:09]   双端观看未完成
```

**Comment by Billyzou0741326** [comment]
有时间我看下 client这边的设计还是不稳2333

**Comment by Billyzou0741326** [comment]
本想逐渐往ts监控加client这边的功能的 结果检测时间区域那块很不好办 就暂时搁置了（主要是我没时间233） 
总之 还是打算以ts的构架写入client功能 App部分全部置换成抽奖代码 大致想法是这样 具体什么时候实现就不好说了…

**Comment by Pearlulu** [comment]
看了下出现Http request errored的时候有上千tcp连接。。
网络问题就是特别费事又费时间，千奇百怪的状况都有，有空再慢慢弄吧

**Comment by Billyzou0741326** [comment]
主要是我的代码问题 这边很多细节都可能造成bug 其实可以稳的
只跑client的话上千那肯定有问题了
有时间就修吧（flag）

**Comment by Billyzou0741326** [comment]
会是抽风暴的时候未能正常停止吗… 无限循环下去的那种情况？

**Comment by Billyzou0741326** [comment]
暂时用dev分支跑吧 当时好像是开了那个分支修bug来着2333

**Comment by Pearlulu** [comment]
我把路由器断网试了下，刷屏同时上万连接数了，运行中断网会刷屏，断网后再启动也会从最开始就一直刷屏。
等晚上研究一下是啥问题。

**Comment by Pearlulu** [comment]
可能是登录信息那里的问题，断网状态下，如果把账号删了就没这个错误，如果有账号就会不断刷屏请求B站api服务器

**Comment by Pearlulu** [comment]
刷屏的原因找到了
bilibili-rest.js里
requestUntilDone里面的循环，有网络的时候tries减到0后就停了
没网络就catch error无限循环了
暂时先在catch error那里加了个sleep 10秒用着

~~频繁报错可能是因为我路由器DNS有问题，重新刷了其他固件，不知道有没有用。~~
频繁报错不是路由器问题，可能还是风暴那里卡住了。

**Comment by Billyzou0741326** [comment]
收到了
不过在这进行的修改… 基本上还是治标不治本 还是得想办法迁移到ts 编译js比较稳

**Comment by Pearlulu** [comment]
很稳定了，一直没出问题

**Comment by Billyzou0741326** [comment]
> 不过在这进行的修改… 基本上还是治标不治本 还是得想办法迁移到ts 编译js比较稳

结果迁移还是咕掉了... 现在也只是凑合着用吧 实在没有时间了
